

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [2]:
import numpy as np

In [7]:
a = np.zeros(10) 
print (a)
type(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.ndarray

In [8]:
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [14]:
np.array(range(10,49))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [17]:
#Create a 3x3 matrix with values ranging from 0 to 8 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
a =[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

In [23]:
#Create a 3x3 identity matrix 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Create a 3x3x3 array with random values
x = np.random.random((3,3,3))
print(x)

[[[0.60976717 0.77439115 0.16604755]
  [0.69016402 0.66039711 0.51774012]
  [0.11463581 0.20219384 0.90281873]]

 [[0.60320332 0.33258927 0.21313471]
  [0.57640918 0.0035392  0.2668605 ]
  [0.64130855 0.98678851 0.98387264]]

 [[0.75590225 0.89212978 0.44743348]
  [0.61346307 0.80480224 0.59042817]
  [0.80055549 0.11862636 0.17314482]]]


In [27]:
#Create a 10x10 array with random values and find the minimum and maximum values

x = np.random.random((10,10))
print("Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("The Minimum and Maximum Values are:")
print(xmin, xmax)

Array:
[[0.7508392  0.75568789 0.13248971 0.47821487 0.51358201 0.77763583
  0.8066548  0.46617971 0.33773683 0.13231517]
 [0.5512968  0.15445303 0.4807554  0.29624024 0.49317905 0.09701409
  0.41991208 0.79757895 0.08167441 0.74545172]
 [0.45610783 0.35738394 0.70743212 0.69374946 0.84942075 0.78755205
  0.52866434 0.82849231 0.35485615 0.67327333]
 [0.51014529 0.41355645 0.09358776 0.36601152 0.37898566 0.09360497
  0.74298036 0.21216828 0.0581075  0.59861185]
 [0.78242384 0.09255744 0.88271546 0.19232054 0.79323627 0.09462194
  0.32451402 0.73151603 0.62573326 0.24257903]
 [0.85966854 0.60069238 0.17437687 0.68920191 0.59128141 0.48538566
  0.76942012 0.75687937 0.2615785  0.8809672 ]
 [0.69188467 0.42386454 0.77767295 0.23849918 0.3334471  0.53401286
  0.72137575 0.29904907 0.72976519 0.40035796]
 [0.72393299 0.35308972 0.55510274 0.61917175 0.61619678 0.04558058
  0.60733449 0.26204601 0.27333902 0.64620529]
 [0.78171499 0.44706563 0.77986293 0.03349447 0.83297084 0.40042766
  0.7

In [28]:
# Create a random vector of size 30 and find the mean value
A = np.random.random(30)
m = A.mean()
print(m)

0.4970771032191499


In [32]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
A = np.diag(1+np.arange(4),k=-1)
print(A)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
# Normalize a 5x5 random matrix 
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.55993796 0.64481698 0.24191078 0.36803339 0.8343401 ]
 [0.48613697 0.86790109 0.1350226  0.3020598  0.61283501]
 [0.00799232 0.35159818 0.14221506 0.48746537 0.75537611]
 [0.30053437 0.03866077 0.49722437 0.16548101 0.68498417]
 [0.01918214 0.77120023 0.57794955 0.12036837 0.40615989]]
After normalization:
[[0.64186535 0.74057235 0.27202707 0.41869683 0.96097146]
 [0.55604114 1.         0.1477253  0.34197521 0.70338007]
 [0.         0.39958409 0.15608952 0.55758595 0.86914312]
 [0.34020127 0.03566478 0.56893483 0.18314582 0.78728335]
 [0.01301281 0.88754522 0.66281128 0.1306837  0.46303467]]


In [34]:
# How to find common values between two arrays?
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [39]:
# Create a random vector of size 10 and sort it

x = np.random.random(10)
print("Original array:", x)

x.sort()
print("Sorted array:", x)


Original array: [0.21150919 0.26794387 0.92498519 0.46217382 0.98203955 0.39685638
 0.02169352 0.1257316  0.87317604 0.9434475 ]
Sorted array: [0.02169352 0.1257316  0.21150919 0.26794387 0.39685638 0.46217382
 0.87317604 0.92498519 0.9434475  0.98203955]


In [42]:
# Create random vector of size 10 and replace the maximum value by 0

x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.84806058 0.83015272 0.31973113 0.97111315 0.64544319 0.98618381
 0.35364894 0.72543973 0.71909647 0.14363251]
Maximum value replaced by 0:
[0.84806058 0.83015272 0.31973113 0.97111315 0.64544319 0.
 0.35364894 0.72543973 0.71909647 0.14363251]


In [47]:
# Subtract the mean of each row of a matrix
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.45648628 0.54203798 0.80223387 0.71178145 0.02261141 0.52389574
  0.84984055 0.16621279 0.90842729 0.75176261]
 [0.35193806 0.08775609 0.96838641 0.87133936 0.74277565 0.17862982
  0.25353829 0.26822806 0.64940631 0.60461755]
 [0.87475898 0.93641776 0.58866853 0.15526992 0.18562221 0.68853122
  0.41981099 0.55805388 0.72946838 0.12323975]
 [0.56548841 0.04605296 0.48886166 0.33673623 0.2336057  0.01847369
  0.78387152 0.09315892 0.66800188 0.27043181]
 [0.7516834  0.12940607 0.85638713 0.0993493  0.46389478 0.02923666
  0.83609178 0.576525   0.1529049  0.53001526]]

Subtract the mean of each row of the said matrix:

[[-0.11704272 -0.03149102  0.22870488  0.13825245 -0.55091759 -0.04963326
   0.27631156 -0.40731621  0.33489829  0.17823361]
 [-0.1457235  -0.40990547  0.47072486  0.3736778   0.24511409 -0.31903174
  -0.24412327 -0.2294335   0.15174475  0.10695599]
 [ 0.34877482  0.4104336   0.06268437 -0.37071425 -0.34036195  0.16254706
  -0.10617318  0.03206972  0.2

In [52]:
# How to get the n largest values of an array
x = np.arange(100)
print("Original array:")
print(x)
np.random.shuffle(x)

n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[99]


In [75]:
# Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

x = np.arange(1, 16).reshape(5,3)
print("Original array:")
print(x)
print("Replace all elements of the said array larger than 4 with their squares ")
x =np.where(x <= 4, x, x**2)
#x[x > 4] = np.square(x>4)
print(x)


Original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Replace all elements of the said array larger than 4 with their squares 
[[  1   2   3]
 [  4  25  36]
 [ 49  64  81]
 [100 121 144]
 [169 196 225]]


In [70]:
x = np.arange(1, 16).reshape(5,3)

In [71]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [74]:
np.where(x <= 4, x, x**2)

array([[  1,   2,   3],
       [  4,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])